export default  {
        Server: Symbol("Server"),
        Application: Symbol("Application"),
        IndexController: Symbol("IndexController"),
        DateController: Symbol("DateController"),
        GameDBController: Symbol("GameDBController"),
        IndexService: Symbol("IndexService"),
        DateService: Symbol("DateService"),
        GameDBService: Symbol("GameDBService"),
        ImageController: Symbol("ImageController"),
        ImageService: Symbol("ImageService"),
        DifferencesService: Symbol("DifferencesService"),
        SoundService: Symbol("SoundService"),
        SoundController: Symbol("SoundController"),
        UserDataBase: Symbol("UserDataBase"),
        FreeDiffService: Symbol("FreeDiffService"),
        ImageControlService: Symbol("ImageControlService"),
        HighscoreService: Symbol("HighscoreService"),
        HighscoreController: Symbol("HighscoreController"),
};
